import os
from datetime import datetime
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from state.research_state import ResearchState

WRITER_SYSTEM_PROMPT = """You are an expert research writer and analyst. Your job is to synthesize 
research findings into a clear, well-structured, professional report.

Your reports must follow this exact markdown structure:
# [Report Title]

## Executive Summary
A 2-3 sentence overview of the key findings.

## Key Findings
Detailed findings organized into logical sections with subheadings.

## Analysis
Critical analysis connecting the findings. Identify trends, implications, and insights.

## Limitations & Caveats
Note any gaps in the research or areas of uncertainty.

## Sources
Numbered list of sources consulted.

---
*Report generated by Multi-Agent Research System*

Write in a professional, objective tone. Use markdown formatting effectively."""


WRITER_USER_PROMPT = """Research Topic: {topic}

Research Findings (across {iterations} research iterations):
{findings}

Critic's Assessment:
{critique}

Sources Consulted:
{sources}

Write a comprehensive, professional research report based on these findings.
Follow the required markdown structure exactly."""


def writer_agent(state: ResearchState) -> ResearchState:
    """
    Writer agent node.
    - Reads all accumulated findings and the critic's assessment
    - Synthesizes a final, structured markdown research report
    - Updates state with the final report
    """
    print(f"\n[Writer] Synthesizing final report for: {state['topic']}")

    llm = ChatGroq(
        model=os.getenv("MODEL_NAME", "llama-3.1-8b-instant"),
        temperature=0.2,
        api_key=os.getenv("GROQ_API_KEY"),
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", WRITER_SYSTEM_PROMPT),
        ("human", WRITER_USER_PROMPT),
    ])

    chain = prompt | llm

    combined_findings = "\n\n---\n\n".join(state.get("raw_findings", []))
    sources_list = "\n".join(
        f"{i+1}. {url}" for i, url in enumerate(state.get("sources", []))
    )

    response = chain.invoke({
        "topic": state["topic"],
        "findings": combined_findings,
        "iterations": state.get("iteration", 1),
        "critique": state.get("critique", "N/A"),
        "sources": sources_list or "No sources recorded.",
    })

    final_report = response.content
    print(f"  [Writer] Report generated ({len(final_report)} characters).")

    return {
        **state,
        "final_report": final_report,
        "status": "done",
    }
